### ISSUE TITLE
Implementierung Imkerbenachrichtigung

### ISSUE THREAD

**Issue by samuelblattner** [openscript/beefindr#11]
# User Story
Als *Imker* möchte ich informiert werden, wenn ein *Naturfreund* einen Bienenschwarm meldet, damit ich den Bienenschwarm einfangen und als neues Bienenvolk halten/bewirtschaften kann.

# Akzeptanzkriterien
- [x] Befinde ich mich nach Luftlinie am nähesten zu einem gemeldeten Bienenschwarm, so werde ich benachrichtigt (E-Mail oder Push)
- [x] Die Benachrichtigung bietet mir die Funktion «Bienenschwarm anschauen» an.
- [x] Betätige ich diese Funktion, gelange ich auf eine Seite, auf der mir die Einzelheiten zum Bienenschwarm angezeigt werden («Einzelheiten» gemäss #10). Idealerweise öffnet sich die Seite direkt in der pwa, ansonsten regulär als Website im Browser)
- [ ] ~~Die Seite stellt die Funktionen «Beanspruchen» und «Verzichten» zur Verfügung.~~ -> Ausgelarget in #30 
- [ ] ~~Betätige ich die Funktion «Beanspruchen», so wird der Bienenschwarm mir zugewiesen. Dies wird mir mit einer entsprechenden Meldung angezeigt.~~ -> Ausgelagert in #32 
- [ ] ~~Betätige ich die Funktion «Verzichten», so wird der Bienenschwarm als nächstes demjenigen Imker angeboten, der sich nach Luftlinie am zweitweitesten entfernt vom Bienenschwarm befindet, usw...~~ -> Ausgelagert in #33
